### ISSUE TITLE
Error when applying numpy.hsplit and numpy.vsplit

### ISSUE THREAD

**Issue by jgoerner** [PacktWorkshops/Data-Visualization-with-Python#2]
#### Description
The showcase  in [Exercise 1.02](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/master/Chapter01/Exercise1.02/Exercise1.02.ipynb) throws a `TypeError` (when applying `hor_split = np.hsplit(dataset, (3))`) followed by a `NameError` (when applying `np.vsplit(hor_splits[0],(2))`.  The first error is due to the fact, that the dataset has a shape of `(24,8)` which can't be split evenly via `np.hsplit(..., (3))`. The second error is due to the failure to assign `hor_split`.

#### Proposed Solution
The simplest solution would be to reassign `dataset` to the transpose of itself (`dataset = dataset.T`).

#### Tasks
- [x] fix [Exercise 1.02](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/master/Chapter01/Exercise1.02/Exercise1.02.ipynb)
- [x] fix [Exercise 1.03](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/d9775862b6a36cdb90b8c00e696201c84b4257e6/Chapter01/Exercise1.03/Exercise1.03.ipynb#L243-L244)

**Comment by jgoerner** [comment]
This also seems to be the case for [Exercise 1.03](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/d9775862b6a36cdb90b8c00e696201c84b4257e6/Chapter01/Exercise1.03/Exercise1.03.ipynb#L243-L244)

**Comment by timgrossmann** [comment]
@jgoerner Thank you for mentioning.
Fixed it, could you please check back and close the issue if resolved? :)

**Comment by jgoerner** [comment]
@timgrossmann 
Could you also add the new dataset `normal_distribution_splittable.csv` to the [datasets folder](https://github.com/PacktWorkshops/Data-Visualization-with-Python/tree/master/Datasets) ?

**Comment by adityashah95** [comment]
@jgoerner the normal_distribution_splittable.csv dataset is now uploaded to the Datasets folder.
