### ISSUE TITLE
Introduction text duplicate

### ISSUE THREAD

**Issue by jgoerner** [PacktWorkshops/Data-Visualization-with-Python#3]
#### Description
The [introduction text of activity 1.02](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/d9775862b6a36cdb90b8c00e696201c84b4257e6/Chapter01/Activity1.02/Activity1.02.ipynb#L14-L15) is the same as for activity 1.01. Additionally it does not reflect the goal, as activity 1.02 uses the `forestfires.csv` dataset (not the `normal_distribution` dataset.

#### Proposed Solution
Adjust the text accordingly to the text of the book.

#### Tasks
- [x] Adjust [activity 1.02](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/master/Chapter01/Activity1.02/Activity1.02.ipynb)

**Comment by timgrossmann** [comment]
@jgoerner Thank you for mentioning.
Fixed it, could you please check back and close the issue if resolved? :)

**Comment by jgoerner** [comment]
👍 looks good
