### ISSUE TITLE
Malformed Notebook (7.03)

### ISSUE THREAD

**Issue by jgoerner** [PacktWorkshops/Data-Visualization-with-Python#4]
#### Description
The Jupyter notebook of [Activity 7.03](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/master/Chapter07/Activity7.03/Activity7.03.ipynb) can't be loaded and the following error is thrown:
```
Unreadable Notebook: .../Data-Visualization-with-Python/Chapter07/Activity7.03/Activity7.03.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')
```

#### Proposed Solution
Find the malformed section and fix the notebook

#### Tasks
- [x] fix [Activity 7.03](https://github.com/PacktWorkshops/Data-Visualization-with-Python/blob/master/Chapter07/Activity7.03/Activity7.03.ipynb)

**Comment by timgrossmann** [comment]
@jgoerner Thanks, just a small bug from manual editing of the ipynb file here on github.

Works now.
