### ISSUE TITLE
Missing Dataset: Tips

### ISSUE THREAD

**Issue by JimLynchCodes** [PacktWorkshops/Data-Visualization-with-Python#6]
Hello, I am trying to do exercise 3.03, visualizing the restaurant tips data in a stacked barchart. 

However, I cannot find the raw tips.cvs data anywhere... 🤔

**Comment by timgrossmann** [comment]
@JimLynchCodes Sorry for the late response and thank you for pointing this out 😊 
We will add the dataset as soon as possible.

**Comment by mariodoebler** [comment]
@JimLynchCodes Apologies from my side as well for the late response. The tips dataset is part of the Seaborn library. You can simply access it as follows:
`bills = sns.load_dataset('tips')`
The tips.csv file will be downloaded in the background. If you want to access the raw tips.csv, you can find it relatively to your python execution path in seaborn-data/tips.csv.
