### ISSUE TITLE
Exercise 6.04 fails at the last command

### ISSUE THREAD

**Issue by cesar-acosta** [PacktWorkshops/Data-Visualization-with-Python#7]
While running your script (works well) however at the last line [12]

# creating the dropdown interaction and building the plot
# based on selection
@interact(Stock=stock_names)
def get_stock_for(Stock='AAPL'):
    stock = dataset[dataset['symbol'] == Stock][:25]
    show(get_plot(stock))

I am getting the following error

AttributeError: unexpected attribute 'legend_label' to Line, possible attributes are js_event_callbacks, js_property_callbacks, line_alpha, line_cap, line_color, line_dash, line_dash_offset, line_join, line_width, name, subscribed_events, tags, x or y

I am using MacOS Mojave and Python 3.7.4

Thank you,
CA

**Comment by timgrossmann** [comment]
@cesar-acosta Sorry for the late reply and thank you for reaching out.

This seems to be a problem with the version of Bokeh you're using.
For the activities and exercises, we've used version 1.4.

Could you please upgrade your bokeh version to the latest version
You can use
```bash
pip install bokeh --upgrade
```

Or install the exact version using
```bash
pip install bokeh==1.4.0
```

You can check the version by using
```bash
pip freeze|grep bokeh
```

Hope that helps 😊
